apiVersion: v1
kind: Service
metadata:
  name: my-flask-service  # Replace with your desired service name
spec:
  type: LoadBalancer
  selector:
    app: my-app  # Match this with the labels in your Deployment's template.metadata.labels
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 5000  # Port on the container
#  type: NodePort  # Exposes the service on a random port on the node's IP






